### ISSUE TITLE
ANS-102: Body

### ISSUE THREAD

**Issue by arweave-kyle** [ArweaveTeam/arweave-standards#1]
Instead of an array at the top level, what do we think about an object?

So currently we have
```
[
  { "sub_tx" },
  { "sub_tx" }
]
```

But maybe something like this?
```
{
  "txs": [
      { "sub_tx" },
      { "sub_tx" }
    ]
}
```

This would gives us a bit of flexibility in future if we want to expand this spec in backwards compatible ways, as we could add more keys later to the top level object, but that's not possible with an array.

**Comment by aidanok** [comment]
This is done 👍
