### ISSUE TITLE
ANS-104: Tags format

### ISSUE THREAD

**Issue by xloem** [ArweaveTeam/arweave-standards#16]
It looks like the specification of the tags in ANS104 is missing the binary encoding for variable length strings.

Working with the source code and data, it seems this format is a binary header-free [Apache Avro](https://avro.apache.org/docs/current/spec.html) array using a schema something like this:
```
{
  "type": "array",
  "items": {
    "type": "record",
    "name": "Tag",
    "fields": [
      { "name": "name", "type": "bytes" },
      { "name": "value", "type": "bytes" }
    ]
  }  
}
```

Existing use of avro to encode tags for ans104 bundles can be seen in https://github.com/Bundlr-Network/arbundles/blob/master/src/parser.ts .

**Comment by rosmcmahon** [comment]
CC @joshbenaron

**Comment by joshbenaron** [comment]
Yep. This also needs to be added. I'd be happy for @xloem to submit a PR. Otherwise I'll tackle this next week.

**Comment by xloem** [comment]
I've drafted documentation of the tags format in #18, formatted at https://github.com/xloem/arweave-standards/blob/patch-2/ans/ANS-104.md#131-tag-format
